### ISSUE TITLE
Does it support nested data on the `fields` declaration?

### ISSUE THREAD

**Issue by marcio0** [toastdriven/restless#11]
As a django-piston user, it is common to have nested data on the fields declaration:

``` python
fields = (
    'id', 'username',
    ('group', ('id', 'name'))
)
```

On django-tastypie, this is similar to use `full = True` on ForeignKey fields.

Is there a way to work with nested data?

**Comment by seocam** [comment]
I'm working on that in the branch `subpreparers`. Stay tuned!

**Comment by seocam** [comment]
This was merged today. Restless 2.1 will be released in a bit! Thanks for the feature request @marcio0!
