### ISSUE TITLE
Drop support for Python < 3.4

### ISSUE THREAD

**Issue by Marcelo-Theodoro** [toastdriven/restless#113]
What are your opinions about dropping support for Python < 3.4? 

Python 2.7 is reaching end-of-life soon. And Python 3.0 to 3.3 are not supported anymore.

Maybe we could give an step foward and drop support for 3.4 too, because it's end of life will be in two months.

This will help us to support new versions of some frameworks while keeping the code clear.

**Comment by Marcelo-Theodoro** [comment]
@seocam Anything to say here?

**Comment by hugovk** [comment]
Drop 3.0 to 3.4.

Once EOL, they no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.5 | 2006-09-19 | 2011-05-26
2.6 | 2008-10-01 | 2013-10-29
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29

Source: https://en.wikipedia.org/wiki/CPython#Version_history

They're also little used. 

Here's the pip installs for restless from PyPI for December 2018:

| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  63.33% |     1,900 |
|      3.6 |  25.23% |       757 |
|      3.7 |   9.30% |       279 |
|      3.5 |   1.17% |        35 |
| null     |   0.83% |        25 |
|      3.4 |   0.13% |         4 |
| Total    |         |     3,000 |

Source: `pypistats python_minor --last-month restless`

**Comment by seocam** [comment]
I'm ok with dropping support from 3.0 to 3.4 (included). @toastdriven anything to add here?

**Comment by hugovk** [comment]
Please see PR https://github.com/toastdriven/restless/pull/116.
