### ISSUE TITLE
Reverse Foreign Key Objects

### ISSUE THREAD

**Issue by Morpho** [toastdriven/restless#34]
Is it possible with restless to get reverse foreign key objects in Django? I.e. I have 2 classes called "Quiz" and "Question" and "Question" has a foreign-key to "Quiz". Now in the detail-view of "Quiz" I would like to show the quiz's title and all related questions.

**Comment by ankitjavalkar** [comment]
Even though this is django specific, For whomsoever may have a similar query

```
class Question(models.Model):
    quiz = models.ForeignKey(Quiz)
    description = models.TextField()

class Quiz(models.Model):
    title = models.CharField(max_length=100)
```

You can do a reverse lookup of foreign keys for a quiz to get all related questions using *question*_set which will return a QuerySet;
```
q = Quiz.objects.get(id=1)
q.question_set.all()
```
