### ISSUE TITLE
self.data should populate from querystring on GET requests

### ISSUE THREAD

**Issue by donspaulding** [toastdriven/restless#50]
I notice that `request.data` is not populated on **GET** requests because almost no HTTP clients send a request _body_ with **GET** requests, even though some client libraries allow it.  On the contrary, when clients want to pass data via **GET**, they (almost always) use querystring arguments.  Wouldn't it make sense for restless to conditionally populate `request.data` from wherever the data is?

**Comment by FFX01** [comment]
You can get the querystring as a dict by using `request.GET.get("parameter")`.

**Comment by seocam** [comment]
I'm not sure that mixing up URL parameters and body in the same data structure is actually a good idea. Does anyone have more inputs on that?

**Comment by FFX01** [comment]
I don't think query string parameters should be in `request.data` as query string parameters are not data; they are queries.

**Comment by donspaulding** [comment]
The idea here is that when many http client libraries allow you to specify data to send to the server along with the request, it's passed in via the same parameter.  Here's how python's `requests` library does it for GET requests:
```
>>> print requests.get("http://httpbin.org/get", {'foo': 'bar'}).text
{
  "args": {
    "foo": "bar"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Connection": "close", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.13.0"
  }, 
  "origin": "XX.XX.XX.XX", 
  "url": "http://httpbin.org/get?foo=bar"
}
```
Notice there's no change to where/how you specify the data parameter when making a POST request:
```
>>> print requests.post("http://httpbin.org/post", {'foo': 'bar'}).text
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "foo": "bar"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Connection": "close", 
    "Content-Length": "7", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.13.0"
  }, 
  "json": null, 
  "origin": "XX.XX.XX.XX", 
  "url": "http://httpbin.org/post"
}
```
What I was asking about is whether it makes sense to mimic this same parity between GET and POST request data on the server side with restless.  I'm not confused about the fact that the querystring is not the same thing as the request body, I'm just pointing out the incongruity between the client and server side here.  

The javascript library `jQuery` does the same thing, FWIW.

**Comment by seocam** [comment]
I see. In `requests` to send query strings you use `params` argument and to send data in the request body you use the `data` argument.

**Comment by donspaulding** [comment]
I'm going to close this issue because it seems pretty limited to just my brain.  Which is fine, I'm used to that.  ;-)

Thanks for the input everyone.
