### ISSUE TITLE
a problem with JSON conversion

### ISSUE THREAD

**Issue by andr2k** [toastdriven/restless#54]
Hello, it looks like something is wrong with JSON-conversion.

Have this code:
```python
from restless.dj import DjangoResource
from restless.preparers import FieldsPreparer
from web.models import *

class SearchRoutesResource(DjangoResource):

    def list(self):
        return {
            'title': 'post.title',
            'author': {
                'id': 'post.user.id',
                'username': 'post.user.username',
                'date_joined': 'post.user.date_joined',
            },
            'body': 'post.content',
        }
```
It returns the following JSON:
```json
{
objects: [
"title",
"body",
"author"
]
}
```

Environment: 
```
python 3.4.0
Django (1.8.3)
pip (7.1.0)
querystring-parser (1.2.0)
restless (2.0.1)
setuptools (18.0.1)
six (1.9.0)
```

**Comment by rkssisodiya** [comment]
The list endpoint handler is expected to return an iterable - which is expected to be a collection of objects to be returned. You are returning a single dictionary and the framework end up iterating on the dictionary ( which is basically an iteration on the keys) and serializing each item in the iteration
This result is coherent with the interface
You need to provide an iterable. Try putting the dictionary you are returning in a list and returning that

**Comment by andr2k** [comment]
Understood it just before your reply. Thank you for the comment.
