### ISSUE TITLE
process_view doesn't get called in middlewares

### ISSUE THREAD

**Issue by Lobosque** [toastdriven/restless#63]
I wonder why the restless endpoints I add to the `urlpatterns` doesn't trigger the process_view function of my django middlewares?

**Comment by seocam** [comment]
If should call middlewares since that's done inside django base handlers class and we don't mess around with that. Can you give us a way to reproduce it?

**Comment by seocam** [comment]
I've just checked using a vanilla setup and it worked as expected. Please let us know if it still happening with you.
