### ISSUE TITLE
JSON fields output not following the same order as defined

### ISSUE THREAD

**Issue by mdsrosa** [toastdriven/restless#70]
If I define a `preparer` like this:

```python
preparer = FieldsPreparer(fields={
    'id': 'id',
    'city': 'city',
    'state': 'state'
})
```
The JSON output:
```json
'{"objects": [{"city": "Sao Paulo",  "state": "SP", "id": 1}]}'
```

And I think the fields should be in the same order as I defined them. Is there a way to change this behavior?

By the way, this happens if I use an `OrderedDict `.

**Comment by mdsrosa** [comment]
No response? Really?

**Comment by issackelly** [comment]
Ordering is not guaranteed in JSON, as per the spec.
