### ISSUE TITLE
Backward-incompatible change introduced

### ISSUE THREAD

**Issue by jaddison** [toastdriven/restless#92]
This simple change results in the breaking of custom resource endpoints: https://github.com/toastdriven/restless/blob/master/restless/dj.py#L93

The documentation for custom endpoints (http://restless.readthedocs.io/en/latest/extending.html#custom-endpoints) establishes that the following will add the desired URL pattern (for a GET request) and work as desired:
```
    # Finally, extend the URLs.
    @classmethod
    def urls(cls, name_prefix=None):
        urlpatterns = super(PostResource, cls).urls(name_prefix=name_prefix)
        return urlpatterns + [
            url(r'^schema/$', cls.as_view('schema'), name=cls.build_url_name('schema', name_prefix)),
        ]
```
However, this is not the case anymore: `http://127.0.0.1/api/posts/schema/` will now get pattern-matches against the PK pattern at https://github.com/toastdriven/restless/blob/master/restless/dj.py#L93.  Either the docs need to be updated to change the order of how the custom URL patterns are built for such a case or the change should be reverted - regardless, I would consider this a backwards incompatible change.

Something like this in docs, maybe?
```
    # Finally, extend the URLs.
    @classmethod
    def urls(cls, name_prefix=None):
        urlpatterns = super(PostResource, cls).urls(name_prefix=name_prefix)
        return [
            url(r'^schema/$', cls.as_view('schema'), name=cls.build_url_name('schema', name_prefix)),
        ] + urlpatterns
```

**Comment by seocam** [comment]
You are totally right @jaddison! I'm sorry for the breaking change. I'm updating the docs.
